# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sebastien/Documents/Projets/Syndesi/syndesicp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sebastien/Documents/Projets/Syndesi/syndesicp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastien/Documents/Projets/Syndesi/syndesicp/CMakeFiles /home/sebastien/Documents/Projets/Syndesi/syndesicp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastien/Documents/Projets/Syndesi/syndesicp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Syndesicp

# Build rule for target.
Syndesicp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Syndesicp
.PHONY : Syndesicp

# fast build rule for target.
Syndesicp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/build
.PHONY : Syndesicp/fast

src/buffer.o: src/buffer.cpp.o
.PHONY : src/buffer.o

# target to build an object file
src/buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/buffer.cpp.o
.PHONY : src/buffer.cpp.o

src/buffer.i: src/buffer.cpp.i
.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s
.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/core.o: src/core.cpp.o
.PHONY : src/core.o

# target to build an object file
src/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/core.cpp.o
.PHONY : src/core.cpp.o

src/core.i: src/core.cpp.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/frame.o: src/frame.cpp.o
.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i
.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s
.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/framemanager.o: src/framemanager.cpp.o
.PHONY : src/framemanager.o

# target to build an object file
src/framemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanager.cpp.o
.PHONY : src/framemanager.cpp.o

src/framemanager.i: src/framemanager.cpp.i
.PHONY : src/framemanager.i

# target to preprocess a source file
src/framemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanager.cpp.i
.PHONY : src/framemanager.cpp.i

src/framemanager.s: src/framemanager.cpp.s
.PHONY : src/framemanager.s

# target to generate assembly for a file
src/framemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanager.cpp.s
.PHONY : src/framemanager.cpp.s

src/framemanagercallbacks.o: src/framemanagercallbacks.cpp.o
.PHONY : src/framemanagercallbacks.o

# target to build an object file
src/framemanagercallbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanagercallbacks.cpp.o
.PHONY : src/framemanagercallbacks.cpp.o

src/framemanagercallbacks.i: src/framemanagercallbacks.cpp.i
.PHONY : src/framemanagercallbacks.i

# target to preprocess a source file
src/framemanagercallbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanagercallbacks.cpp.i
.PHONY : src/framemanagercallbacks.cpp.i

src/framemanagercallbacks.s: src/framemanagercallbacks.cpp.s
.PHONY : src/framemanagercallbacks.s

# target to generate assembly for a file
src/framemanagercallbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/framemanagercallbacks.cpp.s
.PHONY : src/framemanagercallbacks.cpp.s

src/network.o: src/network.cpp.o
.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/payloads.o: src/payloads.cpp.o
.PHONY : src/payloads.o

# target to build an object file
src/payloads.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/payloads.cpp.o
.PHONY : src/payloads.cpp.o

src/payloads.i: src/payloads.cpp.i
.PHONY : src/payloads.i

# target to preprocess a source file
src/payloads.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/payloads.cpp.i
.PHONY : src/payloads.cpp.i

src/payloads.s: src/payloads.cpp.s
.PHONY : src/payloads.s

# target to generate assembly for a file
src/payloads.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/payloads.cpp.s
.PHONY : src/payloads.cpp.s

src/sdid.o: src/sdid.cpp.o
.PHONY : src/sdid.o

# target to build an object file
src/sdid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/sdid.cpp.o
.PHONY : src/sdid.cpp.o

src/sdid.i: src/sdid.cpp.i
.PHONY : src/sdid.i

# target to preprocess a source file
src/sdid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/sdid.cpp.i
.PHONY : src/sdid.cpp.i

src/sdid.s: src/sdid.cpp.s
.PHONY : src/sdid.s

# target to generate assembly for a file
src/sdid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/sdid.cpp.s
.PHONY : src/sdid.cpp.s

src/syndesi_tools.o: src/syndesi_tools.cpp.o
.PHONY : src/syndesi_tools.o

# target to build an object file
src/syndesi_tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/syndesi_tools.cpp.o
.PHONY : src/syndesi_tools.cpp.o

src/syndesi_tools.i: src/syndesi_tools.cpp.i
.PHONY : src/syndesi_tools.i

# target to preprocess a source file
src/syndesi_tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/syndesi_tools.cpp.i
.PHONY : src/syndesi_tools.cpp.i

src/syndesi_tools.s: src/syndesi_tools.cpp.s
.PHONY : src/syndesi_tools.s

# target to generate assembly for a file
src/syndesi_tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Syndesicp.dir/build.make CMakeFiles/Syndesicp.dir/src/syndesi_tools.cpp.s
.PHONY : src/syndesi_tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Syndesicp"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/framemanager.o"
	@echo "... src/framemanager.i"
	@echo "... src/framemanager.s"
	@echo "... src/framemanagercallbacks.o"
	@echo "... src/framemanagercallbacks.i"
	@echo "... src/framemanagercallbacks.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/payloads.o"
	@echo "... src/payloads.i"
	@echo "... src/payloads.s"
	@echo "... src/sdid.o"
	@echo "... src/sdid.i"
	@echo "... src/sdid.s"
	@echo "... src/syndesi_tools.o"
	@echo "... src/syndesi_tools.i"
	@echo "... src/syndesi_tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

